### ISSUE TITLE
Links of hitomi.la containing Japanese characters cannot be downloaded

### ISSUE THREAD

**Issue by lukemin** [HDoujinDownloader/HDoujin-Downloader#12]
Links of hitomi.la containing Japanese characters cannot be downloaded by HdoujinDownloader（Version 2020.12.24.5-1） for status (Page Collection Error).

If the url was encoded to utf-8，then it canbe downloaded by HDoujin-Downloader.
eg.
Saved failed list
[2.manga.zip](https://github.com/HDoujinDownloader/HDoujin-Downloader/files/5805716/2.manga.zip)

**Comment by HDoujinDownloader** [comment]
Thanks for the heads up, and for including the example URLs! 

This is a pretty significant issue. I figured out what was causing it, and the fix will be present in the next update. I'll update this issue when it's uploaded.

**Comment by HDoujinDownloader** [comment]
This issue has been resolved with [Release 2021.1.18.0](https://github.com/HDoujinDownloader/HDoujin-Downloader/releases/tag/v2021.1.18.0).
