### ISSUE TITLE
How are we supposed to contribute if we don't have access to all the code?

### ISSUE THREAD

**Issue by demdante** [HDoujinDownloader/HDoujin-Downloader#4]
The readme states that contributions are welcome, and I wanted to fix the issue outlined [here](https://doujindownloader.com/forum/viewtopic.php?f=9&t=1713), but it is hard to do that when the modules are referencing objects and code that we cannot see.  So, I guess this ticket doubles as fixing the issue linked to above.

**Comment by HDoujinDownloader** [comment]
Thanks-- The site should now be working fully after synchronizing your modules (which occurs automatically at each restart). Fortunately, there was an easier way of getting the image extension. You can see the fix [here](https://github.com/HDoujinDownloader/HDoujin-Downloader/commit/b942bd904aff155f50d0c2e9e3c150b16cc1573c).

I understand that it's hard to contribute when the Lua API is undocumented. I've tried to make it as intuitive as possible, so you should be able to get the gist of it by checking out a few of the existing modules, but I certainly understand this is not an alternative to actual documentation. It's on my to-do list!
