### ISSUE TITLE
Pixiv login doesn't seem to work

### ISSUE THREAD

**Issue by Kuroonehalf** [HDoujinDownloader/HDoujin-Downloader#7]
Hi. For a long while now I've had this issue, and now I decided to finally report it. As the title says, I can't seem to be able to download things from pixiv using my account. I've double checked the password is correct by logging out and logging back in, but when I input the the info into the login manager and then try to scan a pixiv artist link, I always get the error saying the login was unsuccessful. In pixiv you can login with either the username or the email and I've tried both on the login manager, and also with the first letter capitalized, but nothing seems to work.

**Comment by HDoujinDownloader** [comment]
This should finally be fixed with the recent updates I made to the login process in commit 50cb121684ee2e9e6353bae54ee77b516b9afa3a.

Sorry it took so long!
