### ISSUE TITLE
login ehentai with cookies

### ISSUE THREAD

**Issue by lukemin** [HDoujinDownloader/HDoujin-Downloader#9]
Now, Ehentai forum was down. The downloading tasks from ehentai can not  continued due to login in problem. Suffering ehentai and exhentai website via Chrome  with cookies was not affected by this situation.

**Comment by HDoujinDownloader** [comment]
> can not continued

Can you please explain what you mean by this? Downloads from `e-hentai.org` will continue whether or not the login is successful (although `exhentai.org` galleries will not be accessible without login cookies).

HDoujin Downloader will store login cookies after the first successful login, which are visible under `Settings > Downloads > General > Edit Cookies`. You can also [add login cookies here manually](https://doujindownloader.com/faq-i-cant-log-in-to-exhentai-org/), and mark them as "Persistent" to avoid having to login again restarting the program.

**Comment by lukemin** [comment]
> > can not continued
> 
> Can you please explain what you mean by this? Downloads from `e-hentai.org` will continue whether or not the login is successful (although `exhentai.org` galleries will not be accessible without login cookies).
> 
> HDoujin Downloader will store login cookies after the first successful login, which are visible under `Settings > Downloads > General > Edit Cookies`. You can also [add login cookies here manually](https://doujindownloader.com/faq-i-cant-log-in-to-exhentai-org/), and mark them as "Persistent" to avoid having to login again after restarting the program.

but under Settings > logins > if you added accout information. Some hours before, ehentai forum was down, the downloading task from exhentai stopped, and the warning massage is login failed.


22:41:21    hdoujin down[i] CLR Version: 4.0.30319.42000
22:41:21    hdoujin down[i] OS Version: Microsoft Windows NT 6.2.9200.0 (64-bit)
22:41:21    hdoujin down[i] Locale: zh-CN
22:41:21    hdoujin down[i] Path: HDoujin.Downloader-2020.8.8.0-win\HDoujin Downloader.exe
22:41:21    hdoujin down[i] Working Directory: HDoujin.Downloader-2020.8.8.0-win
22:41:21    hdoujin down[i] Timestamp: 2020/12/26 22:41:21
22:41:21    hdoujin down[i] Product Version: 2020.12.24.3-1
22:41:21    hdoujin down[i] Available Security Protocols: SSL 3.0, TLS 1.0, TLS 1.1, TLS 1.2, TLS 1.3
22:41:21    hdoujin down[i] Standalone: False
22:41:21    hdoujin down[i] Repositories: Internal
22:41:21    hdoujin down[i] Theme: Default
22:41:21    config      [i] applying user settings
22:41:21    config      [i] reading download queue
22:41:22    config      [i] saving settings backup
22:41:22    config      [i] applying general settings
22:41:22    config      [i] applying chapters settings
22:41:22    config      [i] applying conversion settings
22:41:22    config      [i] applying metadata settings
22:41:22    config      [i] applying download settings
22:41:22    config      [i] applying accessibility settings
22:41:22    config      [i] applying updater settings
22:41:22    config      [i] applying chapter selection settings
22:41:22    config      [i] applying site-specific settings
22:41:22    config      [i] applying scheduler settings
22:41:22    config      [i] applying login settings
22:41:22    config      [i] reading bookmarks
22:41:22    config      [i] applying bookmarks settings
22:41:22    config      [i] initializing panels
22:41:22    config      [i] applying remaining settings
22:41:22    config      [i] loading download queue columns
22:41:22    config      [!] 7-Zip is not installed
22:41:22    config      [i] finished applying settings
22:41:22    init        [i] registering external module repositories
22:41:22    init        [i] registering external module repository "Official Lua Repository"
22:41:22    init        [i] loading external modules from repository "Official Lua Repository"
22:41:22    official lua[i] Reading metadata cache from modules/Lua\metadata.json
22:41:23    official lua[i] Saving metadata cache
22:41:23    repositories[i] Synchronizing repositories
22:41:23    repositories[i] Synchronizing repository "Official Lua Repository"
22:41:23    official lua[i] Synchronizing repository "Official Lua Repository"
22:41:23    metadata rea[i] Reading metadata from remote repository: https://github.com/HDoujinDownloader/HDoujin-Downloader/tree/master/modules/lua/
22:41:23    metadata rea[i] Reading metadata from GitHub repository (file-list): https://github.com/HDoujinDownloader/HDoujin-Downloader/tree/master/modules/lua/
22:41:23    updater     [i] checking for updates in the background
22:41:23    init        [i] finished initialization
22:41:24    metadata rea[i] Found 72 scripts
22:41:24    official lua[i] Reading metadata cache from modules/Lua\metadata.json
22:41:24    official lua[i] Saving metadata cache
22:41:24    repositories[i] Finished synchronizing repository "Official Lua Repository"
22:41:24    repositories[i] Finished synchronizing repositories
22:41:26    settings    [i] saving repository metadata
22:41:27    login       [i] Attempting to log in to exhentai.org
22:41:27    login       [i] Attempting to log in to exhentai.org
22:41:27    login       [i] Attempting to log in to exhentai.org
22:41:27    login       [i] Attempting to log in to exhentai.org
22:43:07    login       [x] Log in failed

**Comment by Azsesa** [comment]
how do you solve the problem
i just got the same problem
